title: Kismet Sync (Everything and the Kismet Sync)
description: Your site description
    <h1>Welcome to Kismet Sync</h1>
    <p>Bringing together all my passions to help you find balance.</p>

    <h2>Services</h2>
    <ul>
        <li>Life Coaching: Personalized sessions for growth.</li>
        <li>Consulting: Expert advice for your projects.</li>
        <li>Photography: Capturing moments beautifully.</li>
        <li>Painting: Custom artwork.</li>
    </ul>

    <h2>Contact</h2>
    <p>Email: kismetsync777@gmail.com</p>
baseurl: ""
url: "https://github.com/kimijo73/kismetsync-website/blob/main/welcome"  # Replace with your site's URL
markdown: kramdown
theme: minima  # Simple default theme; change if desired
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /blog/:title/  # Sets blog post URLs to /blog/post-title
paginate: 5  # Optional: Paginates posts (5 per page)
paginate_path: "/blog/page/:num/"
# Add Jekyll config for blog.
