title: Kismet Sync (Everything and the Kismet Sync)
description: Your site description
baseurl: ""
url: "https://github.com/kimijo73/kismetsync-website/blob/main/welcome"  # Replace with your site's URL
markdown: kramdown
theme: minima  # Simple default theme; change if desired
plugins:
  - jekyll-feed
  - jekyll-seo-tag
permalink: /blog/:title/  # Sets blog post URLs to /blog/post-title
paginate: 5  # Optional: Paginates posts (5 per page)
paginate_path: "/blog/page/:num/"
# Add Jekyll config for blog.
